title: Plant Humanities Lab
author:
  name: rsnyder
  email: ron@snyderjr.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >-
  Quickly build websites using Github Pages, Markdown, and interactive viewers.

github:
  owner: jstor-labs
  repo: plant-humanities
  branch: gh-pages

url: https://jstor-labs.github.io/plant-humanities/
baseurl: /plant-humanities

layout:
  header: false
  footer: false