title: Plant Humanities
banner: images/ferns.jpg
navigation:
  - path: /
    title: Home
    icon: mdi-home
  - path: /about
    title: About
    icon: mdi-information
  - path: /essays
    title: Visual Essays
    icon: mdi-file-document-outline
  - path: /help
    title: Help
    #source: https://jstor-labs.github.io/visual-essays/help.md
    icon: mdi-help-circle
  - path: /resources
    title: Resources
    icon: mdi-library
  - path: /contact
    title: Contact
    icon: mdi-contact-mail
gh_repo: plant-humanities
context: null
app_version: 0.2.0
lib_version: 0.3.18