title: Mysite starter
banner: https://picsum.photos/1200/225
app_version: 0.1.0
lib_version: 0.3.12
context: null
pages:
  - path: /
    title: Home
    source: index.md
    icon: mdi-home
  - path: /about
    title: About
    source: about.md
    icon: mdi-information
  - path: /help
    title: Help
    source: https://jstor-labs.github.io/visual-essays/help.md
    icon: mdi-help-circle
  - path: /contact
    title: Contact
    source: contact.md
    icon: mdi-contact-mail
